# Project information
site_name: Data Science Project's structure
# defeine TOC or order of website-
nav:
  - Home: index.md
  - 1 Github Repo & Virtual Environment: 1_create_repo_env.md
  - 2 Project folder structure: 2_project_folder_structure.md
  - 3 Custom Exceptions: 3_custom_exception.md
  - 4 Custom Logging: 4_custom_logger.md
  - 5 Common Utilities: 5_common_utilities.md

site_author: Linkan Kumar Sahu
site_description: >-
  DESCRIPTION

# Repository
repo_name: sahulinkan7/Datascience_projects_structures
repo_url: https://github.com/Sahulinkan7/Datascience_projects_structures.git

# Configuration
theme:
  name: material
  features:
    #- navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: blue
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: black
      accent: lime    
  # logo: PyTorch_logo_icon.svg
  
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/Sahulinkan7
    - icon: fontawesome/brands/twitter
      link: https://x.com/sahulinkan7
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/linkan-kumar-sahu/
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/linkan__sahu/

extra_javascript:
  - javascripts/mathjax.js
  # - javascripts/tawk.js
  - https://polyfill.io/v3/polyfill.min.js #?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  
  
plugins:
  - search

copyright: |
  &copy; 2024 <a href="https://github.com/sahulinkan7"  target="_blank" rel="noopener">Linkan Kumar Sahu</a>